from typing import Dict, Any, List, Optional
from nanobot.tools.registry import CapabilityRegistry
from nanobot.core.trust_model import TrustLevel

class NeedleToolAdapter:
    """
    Production Adapter for Cactus Needle 2 Engine (cactus-needle).
    Dispatches tool calls generated by Needle with calibrated confidence gating.
    """
    def __init__(self, registry: Optional[CapabilityRegistry] = None):
        self.registry = registry or CapabilityRegistry()

    def execute_tool_call(self, tool_name: str, arguments: Dict[str, Any]) -> Dict[str, Any]:
        fn = self.registry.get_tool(tool_name)
        if not fn:
            return {
                "status": "error",
                "trust_level": TrustLevel.UNKNOWN,
                "message": f"Unknown tool: '{tool_name}' in Capability Registry."
            }
        try:
            res = fn(**arguments)
            return res
        except Exception as e:
            return {
                "status": "error",
                "trust_level": TrustLevel.UNKNOWN,
                "error": str(e)
            }
